analysis_name: "small-lora-acts-20k-analysis"

metrics: 
  - metric_name: cka
    target_checkpoint: 20_000
    data_split: "val"
    components: 
      - component_name: lora_ov_circuit
        data_type: "activations"
        layer_suffixes: 
          output_layer: "attention.o_proj"
          value_layer: "attention.v_proj"
        layers: [0,1,2,3,4,5,6,7,8,9,10,11]
      - component_name: lora
        data_type: "activations"
        layer_suffixes: "swiglu.w_2"
        layers: [0,1,2,3,4,5,6,7,8,9,10,11]

steps: 
  start: 0
  end: 20_000
  step: 1_000

monitoring: 
  output_dir: "analysis_results"

  save_to_wandb: true
  wandb:
    entity: "pico-lm"
    project: "pico-relora"
