analysis_name: "baseline-swiglu-tiny-analysis"

metrics: 
  - metric_name: per
    data_split: "val"
    components:
      - component_name: simple
        data_type: "weights"
        layer_suffixes: "swiglu.w_2"
        layers: [0,1,2,3,4,5,6,7,8,9,10,11]

steps: 
  start: 0
  end: 20_000
  step: 1000

monitoring: 
  output_dir: "analysis_results"

  save_to_wandb: true
  wandb:
    entity: "pico-lm"
    project: "pico-relora"
